pipeline {
    agent any

    environment {
        DOCKER_COMPOSE_VERSION = '2.27.1'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Git repository
                git branch: 'main', url: 'https://github.com/AvishkaKoswatta/DevOps1_project1.git'
            }
        }
        
        stage('Build and Deploy') {
            steps {
                // Build and deploy using Docker Compose
                script {
                    sh """
                        sudo docker-compose --version || curl -L "https://github.com/docker/compose/releases/download/\${DOCKER_COMPOSE_VERSION}/docker-compose-\$(uname -s)-\$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
                        sudo docker-compose up -d
                    """
                }
            }
        }
    }
    
    post {
        always {
            // Clean up Docker containers and networks
            script {
                sh '''
                    sudo docker-compose down
                    sudo docker volume rm devops1_project1_mysql-data
                '''
            }
        }
    }
}
